name: Prepare Release

on:
  push:
    branches:
        main

  workflow_dispatch:


concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

jobs:

    tag_last_commit:
        name: Tag last commit
        permissions: write-all
        runs-on: ubuntu-latest

        steps:

            - name: Say hello
              run: echo "Hello World"
  
            - name: Generate Tag
              id: generate-tag
              run: echo "tag=$(date '+%y.%j.%H%M')" >> "$GITHUB_OUTPUT"
            
            - name: Set repository variable
              run: |
                curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/alex-pope-l3/github-actions-tag-test/actions/variables/release_tag -d '{'name': 'RELEASE_TAG', 'value': '12.345.6789'}'
                
            - name: Assign tag
              uses: actions/github-script@v7
              with:
                script: |
                  github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: "refs/tags/${{ steps.generate-tag.outputs.tag }}",
                    sha: context.sha
                  })
  