name: Prepare Release

on:
  push:
    branches:
        main

  workflow_dispatch:


concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

jobs:

    tag_last_commit:
        name: Tag last commit
        runs-on: ubuntu-latest

        steps:

            - name: Generate Tag
              id: generate-tag
              run: echo "tag=$(date '+%y.%m.%d')" >> "$GITHUB_OUTPUT"
            
            - name: Create tag on last commit
              uses: actions/github-script@v7
              with:
                script: |
                  github.rest.git.createRef({
                    owner: context.repository_owner,
                    repo: context.repository,
                    ref: "refs/tags/${{ steps.generate-tag.outputs.tag}}",
                  })
