name: Prepare Release

on:
  push:
    branches:
        main

  workflow_dispatch:


concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

jobs:

    tag_last_commit:
        name: Tag last commit
        permissions: write-all
        runs-on: ubuntu-latest

        steps:

            - name: Say hello
              run: echo "Hello World"
  
            - name: Generate Tag
              id: generate-tag
              run: echo "tag=$(date '+%y.%j.%H%M')" >> "$GITHUB_OUTPUT"
            
            - name: Set repository variable
              uses: actions/github-script@v7
              with:
                script: |
                  github.rest.actions.updateRepoVariable({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'RELEASE_TAG',
                    value: '${{ steps.generate-tag.outputs.tag }}'
                  })
                
            - name: Assign tag
              uses: actions/github-script@v7
              with:
                script: |
                  github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: "refs/tags/${{ steps.generate-tag.outputs.tag }}",
                    sha: context.sha
                  })
  